#
#  MPLAB X Generated Makefile - ATU130
#  PIC18F2520 / XC8
#

# Environment
MKDIR=mkdir
CP=cp
CCADMIN=CCadmin
RANLIB=ranlib


# build
build: .build-post

.build-pre:

.build-post: .build-impl


# clean
clean: .clean-post

.clean-pre:

.clean-post: .clean-impl


# clobber
clobber: .clobber-post

.clobber-pre:

.clobber-post: .clobber-impl


# all
all: .all-post

.all-pre:

.all-post: .all-impl


# help
help: .help-post

.help-pre:

.help-post: .help-impl



# include project implementation makefile
include nbproject/Makefile-impl.mk

# include project make variables
include nbproject/Makefile-variables.mk

# include local overrides (machine-specific paths, extra sources)
# MPLAB X generise ovaj fajl pri otvaranju projekta
-include nbproject/Makefile-local-default.mk
